use_frameworks!

platform :ios, '8.0'

target 'LYVideosPlayer_Example' do
  pod 'LYVideosPlayer', :path => '../'

  target 'LYVideosPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
